version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - '8081:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sampleuser
      WORDPRESS_DB_PASSWORD: samplepass
      WORDPRESS_DB_NAME: sampledb
    volumes:
      - .:/var/www/html/wp-content/themes/wp-crude
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3307:3306'
volumes:
  db_data: {}
